# Generated by Django 2.2.6 on 2019-10-01 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('XIAOMI', 'Xiaomi')], max_length=30)),
                ('model_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1019)])),
            ],
        ),
    ]
