# Generated by Django 2.2.6 on 2019-10-01 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('date_release', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modify', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.PhoneModel')),
            ],
        ),
    ]
