# Generated by Django 2.2.6 on 2019-10-03 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker', models.CharField(max_length=80)),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('column', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('part', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Part')),
                ('phone', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Phone')),
            ],
        ),
    ]
