# Generated by Django 2.2.6 on 2019-11-07 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='condition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='condition',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default=('ACTIVE', 'Active'),
                                   max_length=30),
        )
    ]
