# Generated by Django 2.2.6 on 2019-11-07 15:55

from django.db import migrations, models
import django.db.models.deletion


def move_data(apps, schema_editor):
    Storage = apps.get_model('storage', 'Storage')
    Device = apps.get_model('storage', 'Device')
    queryset = Storage.objects.all()
    for storage in queryset:
        device = None
        if storage.phone and not Device.objects.filter(phone=storage.phone).exists():
            device = {'phone': storage.phone}
        elif storage.part and not Device.objects.filter(part=storage.part).exists():
            device = {'part': storage.part}
        if device:
            device_instance = Device(**device)
            device_instance.save()
            storage.device = device_instance
            storage.save()
        else:
            storage.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0005_phone_condition_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='storage.Part')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='storage.Phone')),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='device',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='storage.Device'),
        ),

        migrations.AlterField(
            model_name='device',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='storage.Part', unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='storage.Phone', unique=True),
        ),

        migrations.AlterField(
            model_name='device',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='storage.Part', unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='storage.Phone', unique=True),
        ),
        migrations.RunPython(move_data),
        migrations.RemoveField(
            model_name='storage',
            name='part',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='phone',
        ),
        migrations.AlterField(
            model_name='storage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Device'),
        ),
    ]
